---
depends_on: []
kind: pipeline
name: pr-build-e2e
node:
  type: no-parallel
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v2.9.33/grabpl
  - chmod +x bin/grabpl
  image: byrnedo/alpine-curl:0.1.8
  name: grabpl
- commands:
  - ./bin/grabpl gen-version --build-id ${DRONE_BUILD_NUMBER}
  depends_on:
  - grabpl
  image: grafana/build-container:1.5.3
  name: gen-version
- commands:
  - make gen-go
  depends_on:
  - grabpl
  image: grafana/build-container:1.5.3
  name: wire-install
- commands:
  - yarn install --immutable
  depends_on:
  - grabpl
  image: grafana/build-container:1.5.3
  name: yarn-install
- commands:
  - ./bin/grabpl build-frontend --jobs 8 --edition oss --build-id ${DRONE_BUILD_NUMBER}
  depends_on:
  - gen-version
  - yarn-install
  environment:
    NODE_OPTIONS: --max_old_space_size=8192
  image: grafana/build-container:1.5.3
  name: build-frontend
trigger:
  event:
  - pull_request
  paths:
    exclude:
    - docs/**
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gcr
kind: secret
name: dockerconfigjson
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: github_token
---
get:
  name: machine-user-token
  path: infra/data/ci/drone
kind: secret
name: drone_token
---
get:
  name: bucket
  path: infra/data/ci/grafana/prerelease
kind: secret
name: prerelease_bucket
---
get:
  name: credentials.json
  path: infra/data/ci/grafana/releng/artifacts-uploader-service-account
kind: secret
name: gcp_upload_artifacts_key
---
kind: signature
hmac: b9667bf887a46e014ff171cb4621090679fdec47dad3b189bcf9e151eac57bb9

...
